{% set name = "koolstof" %}
{% set version = "0.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/koolstof-{{ version }}.tar.gz
  sha256: 0fd636e0410844f6c8b6e70794f981a0a5bf92f01544f6f7fc0f79439103ce9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - calkulate
    - matplotlib-base
    - numpy
    - pandas
    - pyco2sys
    - scikit-learn
    - scipy
    - seaborn
    - pip
  run:
    - python >=3.7
    - calkulate
    - matplotlib-base
    - numpy
    - pandas
    - pyco2sys
    - scikit-learn
    - scipy
    - seaborn

test:
  imports:
    - koolstof
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Miscellaneous tools for marine carbonate chemistry
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/koolstof

extra:
  recipe-maintainers:
    - mvdh7
