{% set name = "koolstof" %}
{% set version = "0.31" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/koolstof-{{ version }}.tar.gz
  sha256: 1ff38cfa14b8c9b93b8d059191dac86e176e0a68ad49aa500b2d5e925af57c7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - calkulate
    - matplotlib-base
    - numpy
    - pandas
    - pyco2sys
    - scikit-learn
    - scipy
    - seaborn

test:
  imports:
    - koolstof
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Miscellaneous tools for marine carbonate chemistry
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/koolstof

extra:
  recipe-maintainers:
    - mvdh7
