{% set name = "koolstof" %}
{% set version = "0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/c8/75/09a16ec6a608c0d893852ac852328a3cd82653549eeab9d2f104152337cb/koolstof-0.27.tar.gz
  sha256: fd51d2e68aa7723bcee91f4db1c0c3338445e8ec65017b491049702e246ca80f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - calkulate
    - matplotlib-base
    - numpy <=1.23
    - pandas
    - pyco2sys
    - scikit-learn
    - scipy
    - seaborn
    - pip
  run:
    - python >=3.7
    - calkulate
    - matplotlib-base
    - numpy <=1.23
    - pandas
    - pyco2sys
    - scikit-learn
    - scipy
    - seaborn

test:
  imports:
    - koolstof
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Miscellaneous tools for marine carbonate chemistry
  license: GPL-3.0-only
  license_file: LICENSE
  home: https://github.com/mvdh7/koolstof

extra:
  recipe-maintainers:
    - mvdh7
